name: Update Algolia Search Index

on:
  push:
    branches:
      - main
    paths:
      - "content"
  workflow_dispatch:

jobs:
  algolia-atomic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # use the environment variable HUGO_VERSION as the hugo version, if not set, use `latest`.
          hugo-version: ${{ vars.HUGO_VERSION || 'latest' }}
          extended: true

      - name: Install Dependencies
        run: |
          npm install -g atomic-algolia

      - name: Build
        run: |
          npm install
          npm run build

      - name: Update Algolia Index
        env:
          ALGOLIA_APP_ID: JQ10L16U5A
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        run: |
          ALGOLIA_INDEX_NAME="search" ALGOLIA_INDEX_FILE="public/search.json" npm run algolia